short_code = input().lower()
    # if short_code == 'nu':
    #     print ('\n Create new account here')
    #     print ('new passwordlocker account')
    #     print('_'*10)
    #     print('username ..')
    #     username = input()
    #     while True:
    #         print("Enter a password for your account")
    #         print(" "*4 + "*the password must be 5 characters or longer*")
    #         while True:
    #             print('if you would like autogenerated password type in  AG else type in OG for self generated')
    #             password_choice = input().lower().strip()
    #             if password_choice == 'ag':
    #                 password1 = input('add your password')
    #                 password2 = input ('kindly repeat the password')
    #                 if password1 == password2:
    #                     password = password1
    #                     break
    #                 else:
    #                     print('*'*20)
    #                     print('the passwords do not math. Repeat the process.')
    #                     print('*'*20)
                        
    #             elif password_choice == 'og':
    #                 password = generate_a_password()
    #                 break
    #             else:
    #                 print('You made an invalid choice. Kindly try once more')

    
    # elif short_code =='lg':
    #     print ('_'*20)
    #     print('log in into the passwordlocker account')
    #     print('enter your username')
    #     username = input()
    #     print('password')
    #     password = input()
    #     print('\n')
        
    #     if check_existing_user(username, password):
    #         print('\n succesful login')
            
    #         while True:
    #             print('use short codes to navigate to what you want to do.\n CC: Create new credentials \nDC: delete a credential \n FC: Find credentials \nVC: View all credentials')
    #             short_code = input().lower()
                
    #             if short_code == 'CC':
    #                 print('\n Create new credentials')
    #                 print('_'*10)
    #                 while True:
    #                     print('Application name:')
    #                     app_name = input()
    #                     if app_name !='':
    #                         account_username = input()
                            
    #                         while True:
    #                             print ('Do you have a current password on' + {app_name} + 'Y/N' )
    #                             existing_password = input()
    #                             if existing_password =='Y':
    #                                 print ( 'Input your ' + {app_name} + 'password' )
    #                                 account_password = input()
    #                                 save_credentials(create_credentials(
    #                                     app_name, account_username, account_password))
    #                                 print(' Account credentials for' + {app_name} +  'under you name were created ')
    #                                 break
                                
    #                             elif existing_password == 'N':
    #                                 while True:
    #                                     print('enter your preffered password to use on' + {app_name} )
    #                                     account_password = input()
    #                                     save_credentials(create_credentials(
    #                                         app_name, account_username, account_password))
    #                                     print ('Account details for' + {app_name} + 'were successfully created ')
    #                                     break
                                    
    #             elif short_code == 'FC':
    #                 print('\n find credentials')
    #                 print('_'*10)
    #                 print('\eg Instagram')
    #                 searched_app = input()
                    
    #                 if check_existing_credentials(searched_app):
    #                     searched_credential = find_credentials(searched_app)
    #                     print('app-name:' + {searched_app.app_name} + {searched_credential.account_username} + 'password:' + {searched_credential.account_password} )
                        
    #                 else:
    #                     print('Sadly, we coud not find the' + {searched_app} + 'credentials')
                        
    #                     continue
                
    #             elif short_code == 'DC':
    #                 print(' delete credentials')
    #                 app_name= input()
                    
    #                 if check_existing_credentials(app_name):
    #                     while True:
    #                         print('you sure you wanna do that to your' + {app_name} + 'Y/N')
    #                         delete_credential = input()
    #                         if delete_credential == 'Y':
    #                             remove_credentials(find_credentials(app_name))
    #                             print('Your credentials were successfully removed for' + {app_name} )
                                
    #                         elif delete_credential == 'N':
    #                             print('\n your credentials have remained here. ')
    #                             break
    #                         else: 
    #                             print('kindly select a valid option try again either Yes or No (Y/N')
    #                             continue
                    
    #                 else:
    #                     print ('credentials for the' +  {app_name} + 'do not exist')
    #                     continue
                        
    #             elif short_code == 'VC':
    #                 display_credentials
    #                 print('\n view all your credentials here')
    #                 print('_'*10)
    #                 for credential in display_credentials():
    #                     print ('App name:' + {credential.app_name} + 'Username:' + {credential.account_username} + 'Password:' + {credential.account_password} )
    #                     continue
    #                 else:
    #                     print('\n Kindly add your details to the lists')
    #                     continue
                    
    #             elif short_code == 'ex':
    #                 print('you successfully left the application')
                
    #             else:
    #                 print('\n You did not select a valid option here')
    #                 print('\n kindly try again')
    #                 continue
                
    #     else:
    #         print('did you add anything?')

